// Source declarations for the package. Edit this file; dist/index.d.ts is generated by `npm run build`.

import * as Backbone from 'backbone';

export type Id = string | number;

export type ModelConstructor<TModel extends Backbone.Model = Backbone.Model> = {
  new(attributes?: Record<string, unknown>, options?: Backbone.ModelSetOptions): TModel;
};

export type StoredModelConstructor<TModel extends Backbone.Model = Backbone.Model> =
  ModelConstructor<TModel> & typeof Backbone.Model;

export interface Inspection<TModel extends Backbone.Model = Backbone.Model> {
  modelName: string;
  id: unknown;
  key: string | undefined;
  cached: boolean;
  model: TModel | undefined;
}

export interface ModelCache<TModel extends Backbone.Model = Backbone.Model> {
  readonly instances: Readonly<Record<string, TModel>>;
  Model: ModelConstructor<TModel>;
  modelName: string;
  ModelConstructor: StoredModelConstructor<TModel>;
  get(attributes?: Record<string, unknown>, options?: Backbone.ModelSetOptions): TModel;
  find(id: unknown): TModel | undefined;
  has(id: unknown): boolean;
  patch(
    id: unknown,
    attributes: Record<string, unknown>,
    options?: Backbone.ModelSetOptions
  ): TModel | undefined;
  evict(id: unknown): TModel | undefined;
  inspect(id: unknown): Inspection<TModel>;
  reset(): void;
  remove(instance: TModel): TModel;
}

export interface StoreStatic extends Backbone.EventsMixin {
  <TModel extends Backbone.Model>(
    Model: ModelConstructor<TModel>,
    modelName?: string
  ): StoredModelConstructor<TModel>;

  ModelCache: {
    new<TModel extends Backbone.Model>(
      Model: ModelConstructor<TModel>,
      modelName: string
    ): ModelCache<TModel>;
  };

  add<TModel extends Backbone.Model>(
    Model: ModelConstructor<TModel>,
    modelName: string
  ): ModelCache<TModel>;
  getCache<TModel extends Backbone.Model = Backbone.Model>(modelName: string): ModelCache<TModel>;
  get<TModel extends Backbone.Model = Backbone.Model>(modelName: string): StoredModelConstructor<TModel>;
  getAllCache(): Record<string, ModelCache>;
  find<TModel extends Backbone.Model = Backbone.Model>(modelName: string, id: unknown): TModel | undefined;
  has(modelName: string, id: unknown): boolean;
  patch<TModel extends Backbone.Model = Backbone.Model>(
    modelName: string,
    id: unknown,
    attributes: Record<string, unknown>,
    options?: Backbone.ModelSetOptions
  ): TModel | undefined;
  evict<TModel extends Backbone.Model = Backbone.Model>(modelName: string, id: unknown): TModel | undefined;
  inspect<TModel extends Backbone.Model = Backbone.Model>(modelName: string, id: unknown): Inspection<TModel>;
  getAll(): Record<string, StoredModelConstructor>;
  reset(modelName: string): void;
  resetAll(): void;
  remove(modelName: string): void;
  removeAll(): void;
}

export const ModelCache: StoreStatic['ModelCache'];

declare const Store: StoreStatic;

export default Store;
